"""Add billing run, proposal and proposal line tables

Revision ID: 385ac3828e5e
Revises: b31259bb8b0d
Create Date: 2026-09-27 22:14:28.600640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385ac3828e5e'
down_revision = 'b31259bb8b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'year', 'month', name='uq_billing_run_month')
    )
    with op.batch_alter_table('billing_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_run_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_run_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('vat_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['billing_run_id'], ['billing_run.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billing_run_id', 'client_id', name='uq_proposal_client')
    )
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_billing_run_id'), ['billing_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proposal_client_id'), ['client_id'], unique=False)

    op.create_table('proposal_line',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['proposal.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proposal_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proposal_line_proposal_id'), ['proposal_id'], unique=False)

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposal_line_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_activity_proposal_line_id'), ['proposal_line_id'], unique=False)
        batch_op.create_foreign_key(None, 'proposal_line', ['proposal_line_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_activity_proposal_line_id'))
        batch_op.drop_column('proposal_line_id')

    with op.batch_alter_table('proposal_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_line_proposal_id'))

    op.drop_table('proposal_line')
    with op.batch_alter_table('proposal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proposal_client_id'))
        batch_op.drop_index(batch_op.f('ix_proposal_billing_run_id'))

    op.drop_table('proposal')
    with op.batch_alter_table('billing_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_run_tenant_id'))

    op.drop_table('billing_run')
    # ### end Alembic commands ###
